name: Frontend CI
on: [push]
jobs:
  prettier:
    name: formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - run: cd frontend
      - run: bun install
      - run: bun run format --check

  vitest:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - run: cd frontend
      - run: bun install
      - run: bun run test:unit
  
  cypress:
    name: integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      # tbh, using bun here is useless. It just runs vite anyway. Maybe faster install time tho?
      - run: cd frontend
      - run: bun install
      - run: bun run build
      - run: bun run test:e2e